name: Python Package Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest pytest-cov
        # Install the package in development mode
        pip install -e .
        
    - name: Test with pytest
      run: |
        pytest tests/

  # Additional job to test with all optional dependencies
  test-full:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"
        
    - name: Install dependencies with extras
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest pytest-cov
        # Install the package with all optional dependencies
        pip install -e ".[dev,ml]"
        
    - name: Test with pytest
      run: |
        pytest tests/ 